### ISSUE TITLE
Wrongly auto-linking email addresses as mentions.

### ISSUE THREAD

**Issue by SirRawlins** [twitter-archive/twitter-text-rb#123]
It seems that the auto_link method is wrongly detecting email addresses as mentions and linking them.

```
Twitter::Autolink.auto_link_usernames_or_lists 'My email is robert@weboffins.com'
 => "My email is robert@<a class=\"tweet-url username\" href=\"https://twitter.com/weboffins\" rel=\"nofollow\">weboffins</a>.com" 
```

This feels counter intuitive to me as it creates invalid links, and also present conflicts when used with the `rinku` gem for linking emails with mailto://

**Comment by jakl** [comment]
Thanks - now fixing in the new twitter-text mono-repo.
On rinku, their goals are a little different. Twitter-text makes linking behavior predictable/reproducable with twitter.com supporting slang/patterns in common languages on twitter.
