### ISSUE TITLE
Newlines break hashtag extraction

### ISSUE THREAD

**Issue by sferik** [twitter-archive/twitter-text-rb#15]
I'm trying to extract the hashtags from the text of [this Tweet](https://twitter.com/blasphemydrive/status/136729600154800128) using the `Twitter::Extractor.extract_hashtags` method.

It's hard to see on the Twitter website, but the text string contains various newline characters:

``` ruby
"#bieber\n#justinbieber \n#bangersgarlingistrending \nRT if you are mega excited about biebs' 'secret' show coming in January to The Metro"
```

I expect the result to be:

``` ruby
["bieber", "justinbieber", "bangersgarlingistrending"]
```

instead of just:

``` ruby
["bangersgarlingistrending"]
```

**Comment by keitaf** [comment]
Thank you for finding the bug. I made a fix for this.
I added test cases in the conformance test
https://github.com/twitter/twitter-text-conformance/pull/18
and made a fix on twitter-text-rb
https://github.com/twitter/twitter-text-rb/pull/17
