### ISSUE TITLE
No read access to gem installing via sudo

### ISSUE THREAD

**Issue by brightchimp** [twitter-archive/twitter-text-rb#16]
Installing this gem via sudo give root user read access to the files.

Install gem:

```
sudo gem install 'twitter-text' --version 1.4.13
```

Start irb

```
require 'rubygems'
require 'twitter-text'
=> LoadError: no such file to load -- twitter-text
```

All files in /usr/lib/ruby/gems/1.8/gems/twitter-text-1.4.13/lib permissions of 660 (rw-rw----). I needed to manually add read permissions for non-root users to all files in the lib directory.

**Comment by seldo** [comment]
We also ran into this on twitter-text v 1.4.12 and 1.4.13.

**Comment by mikebannister** [comment]
I got bit by this also. Anyone have a guess what might cause this? Manually chmodding +r in lib/ fixed things here but it'd be nice if we could fix the root cause.

**Comment by heaven** [comment]
The same issue with 1.4.13

**Comment by heaven** [comment]
[deploy@vs246911 lib]$ ls -l
total 64
-rw-r----- 1 root rvm  9239 Nov 29 15:02 autolink.rb
-rw-r----- 1 root rvm  9082 Nov 29 15:02 extractor.rb
-rw-r----- 1 root rvm  3017 Nov 29 15:02 hithighlighter.rb
-rw-r----- 1 root rvm 14930 Nov 29 15:02 regex.rb
-rw-r----- 1 root rvm  2015 Nov 29 15:02 rewriter.rb
-rw-r----- 1 root rvm   745 Nov 29 15:02 twitter-text.rb
-rw-r----- 1 root rvm   916 Nov 29 15:02 unicode.rb
-rw-r----- 1 root rvm  4148 Nov 29 15:02 validation.rb

**Comment by davidmainzer** [comment]
I updated to version 1.4.15 ... 

maxwell lib # ls -l
total 64
-rw-rw-r-- 1 root root  9443 Dec  6 15:40 autolink.rb
-rw-rw-rw- 1 root root  9305 Dec  6 15:40 extractor.rb
-rw-rw-rw- 1 root root  3017 Dec  6 15:40 hithighlighter.rb
-rw-rw-rw- 1 root root 15066 Dec  6 15:40 regex.rb
-rw-rw-rw- 1 root root  2015 Dec  6 15:40 rewriter.rb
-rw-rw-rw- 1 root root   745 Dec  6 15:40 twitter-text.rb
-rw-rw-rw- 1 root root   916 Dec  6 15:40 unicode.rb
-rw-rw-rw- 1 root root  4148 Dec  6 15:40 validation.rb
maxwell lib # chmod --help

autolink.rb -- forgot to add read permissions for other

why others have write permissions for all files? Thats a security issue i think!

Best :)

**Comment by edmundsalvacion** [comment]
+1

This is still an issue for 1.5.0.

**Comment by stephanschielke** [comment]
@edmundsalvacion +1 I too have problems in 1.5.0.

**Comment by jakl** [comment]
Is this fixed now? All my files have permission 644 after a sudo gem install twitter-text
