### ISSUE TITLE
a bug of auto_link_usernames_or_lists when deal with html

### ISSUE THREAD

**Issue by blankyao** [twitter-archive/twitter-text-rb#18]
The auto_link_usernames_or_lists can't deal with html well.

for example:

``` ruby
auto_link_usernames_or_lists('<p>@blankyao</p>')
```

it return the text without any link.

**Comment by jakl** [comment]
Should be working

**Comment by sunnybogawat** [comment]
am facing same issue when I am trying to generate link using html tag. when you have mention string inside single html element then it not generate link but if you have more than two tag it generate link correctly
Example:- 

![Screenshot](https://f.cloud.github.com/assets/250483/395968/091311b0-a813-11e2-8c86-456c5a5def94.png)

**Comment by ahmedyehia** [comment]
i tried this and it is working correctly for both

**Comment by jakl** [comment]
Looks alright on latest version.
