### ISSUE TITLE
extractor.rb:161: duplicated argument name (SyntaxError) 

### ISSUE THREAD

**Issue by jadeydi** [twitter-archive/twitter-text-rb#20]
In this file 

I got "text.scan(Twitter::Regex[:auto_link_hashtags]) do |before, hash, hash_text, hash|"

Why there are two "hash" ?

**Comment by keitaf** [comment]
line 230 of the latest lib/extractor.rb on master (https://github.com/twitter/twitter-text-rb/blob/master/lib/extractor.rb) is

"text.scan(Twitter::Regex[:auto_link_hashtags]) do |before, hash, hash_text|"

Can you please specify which version of twitter-text-rb you are looking at?

**Comment by jadeydi** [comment]
my Gemfile: gem 'twitter-text' , :git => "git://github.com/caryl/twitter-text-rb.git"

error: gems/twitter-text-rb-0f8978d326af/lib/extractor.rb:161: duplicated argument name

**Comment by jadeydi** [comment]
I'm sorry, write at the wrong place
