### ISSUE TITLE
Cannot extract international text with correct indice in a rails project

### ISSUE THREAD

**Issue by larryzhao** [twitter-archive/twitter-text-rb#48]
I was playing with it in my rails console (jruby-1.6.7, rails 3.2) and found things were not quite correct if I extract mentions/hashtags with japanese or chinese text with indices, the screen name was correctly returned, but the indices is not correct.

Then I created a spec in my rails project and copied from twitter-text-rb/spec/extrator_spec into it, and I got failed tests if I run it in my rails project. I created a gist for the results. https://gist.github.com/2204246

Is there any settings to be done for it could be used in a rails project?

I have the `Encoding.default_external` and `Encoding.default_internal` already set to `Encoding::UTF_8`

**Comment by jakl** [comment]
Should be fixed - not sure jruby differences will be supported
