### ISSUE TITLE
ruby 1.8.7 KCODE

### ISSUE THREAD

**Issue by harry-wood** [twitter-archive/twitter-text-rb#5]
I just spent ages trying to get this to work on ruby 1.8.7 and rubygems 1.5.3.  Now I have it working. At the top of my script I needed to do:

``` ruby
require 'rubygems'
$KCODE='u'
require 'twitter'
require 'twitter-text'
include Twitter::Autolink 

```

 KCODE='u'  is a bit of magic I found at the bottom of a discussion on a google cached copy of the old issue tracker here: http://webcache.googleusercontent.com/search?q=cache:iAS36VNIoLYJ:https://github.com/mzsanford/twitter-text-rb/issues/8+twitter-text+requires+the+%24KCODE+variable+be+set+to+%27UTF8%27&cd=5&hl=en&ct=clnk&client=ubuntu 

(took me a while to find!)   As I say, I got it working,  so this is maybe just a comment on the documentation, or not even that.

**Comment by ghost** [comment]
Still appears to be a problem. See https://github.com/jnunemaker/twitter/issues/213
