### ISSUE TITLE
Errant documentation in README

### ISSUE THREAD

**Issue by tricon** [twitter-archive/twitter-text-rb#63]
`lib/autolink.rb` includes a custom version of `link_to`. This clobbers Rails' `link_to` definition and fails on `link_to` calls that utilize a block. `link_to` should be enhanced, renamed, or the following should be removed from the documentation:

```
# For Ruby on Rails you want to add this to app/helpers/application_helper.rb
module ApplicationHelper
  include Twitter::Autolink
end
```

Would a patch for any of these solutions be accepted?

**Comment by niw** [comment]
Understand, will rename the method.

**Comment by fetsh-legacy** [comment]
It still "fails on link_to calls that utilize a block". &lt;html tags&gt; inside block becomes escaped: &amp;lt;html tags&amp;gt;
