### ISSUE TITLE
Escaping HTML

### ISSUE THREAD

**Issue by thebusiness11** [twitter-archive/twitter-text-rb#77]
When using  <%= auto_link("link @user, please #request") %>

It returns escaped html in the view, I cant find a way to get usable HTML

**Comment by thebusiness11** [comment]
If you add .html_safe it works correctly, just not in any docs.

**Comment by juanpujol** [comment]
I solved my problem using sanitize.

`<%= raw auto_link(sanitize(comment.body, tags: %w(a), attributes: %w(class)), autolink_options) %>`
