### ISSUE TITLE
Auto link and convert t.co urls

### ISSUE THREAD

**Issue by timmillwood** [twitter-archive/twitter-text-rb#78]
[feature request]
Would it be possible to convert t.co domains to the full / original domain when autolinking them?

**Comment by calebhearth** [comment]
Even better, recognize link shorteners in general and unshorten them recursively until you get a raw link

**Comment by jakl** [comment]
This would be part of the t.co project instead of twitter-text, but here is how to use curl to recursively expand short urls:

expandurl () { #find the final landing page of a short url like t.co/UgSnleeKua
  curl -sIL $1 | grep ^Location: | tail -n1 | sed 's/Location: //'
}
