### ISSUE TITLE
Link break for mention string having '-' character

### ISSUE THREAD

**Issue by sunnybogawat** [twitter-archive/twitter-text-rb#84]
My mention string has hyphen in between when I am trying to create link it break because of '-'.

 mention_str = "sunny-b"
 puts Twitter::Autolink.auto_link(mention_str, :username_include_symbol => true) 

 O/P  - <a href="">sunny</a>-b with invalid URL

**Comment by jakl** [comment]
Hyphens can't be in @mentions or @usernames
Should be working correctly
