### ISSUE TITLE
Conform to the Developer Display Requirements when linking usernames

### ISSUE THREAD

**Issue by jalada** [twitter-archive/twitter-text-rb#93]
The [Developer Display Requirements](https://dev.twitter.com/terms/display-requirements) state (in a roundabout way) that the "@" symbol and the username must link to the Twitter profile (not just the username), but autolink only links the username, not the @ symbol as well.

Background: We're trying to get Site Streams access and this was raised as an issue via email.

**Comment by jakl** [comment]
Is this what you needed?
twttr.txt.autoLink('@asdf', { usernameIncludeSymbol: true })

**Comment by jakl** [comment]
You can quickly test this in the javascript console on [tweetdeck](https://web.tweetdeck.com)

**Comment by jalada** [comment]
Thanks, looks like that's it; was hard to spot at first glance.

**Comment by jakl** [comment]
Thanks for pointing out the style guide - maybe this should be default now.
