### ISSUE TITLE
Please release 1.6.2 to rubygems

### ISSUE THREAD

**Issue by grosser** [twitter-archive/twitter-text-rb#96]
would allow us to kill a git dependencies :)
@caniszczyk @jakl

**Comment by caniszczyk** [comment]
@jakl did you update the release here? https://github.com/twitter/twitter-text-rb/releases

**Comment by caniszczyk** [comment]
@jakl did you tag the release?

**Comment by grosser** [comment]
the source-code-url in the gemspec still points to https://github.com/mzsanford/twitter-text-rb

**Comment by jakl** [comment]
Separate pull request please. Also sorry I pushed the tag a little after the gem. 1.6.3 coming now to include some more pull requests.

**Comment by caniszczyk** [comment]
Thank you!
